package world.phantasmal.web.assetsGeneration.psov2

/**
 * One enemy's psov2 source data. Derived by scanning psov2's AssetEnemies.js for each entry's
 * NinjaFile.API.load/gsl/bml calls -- unlike player classes, enemy texture IDs index directly
 * into their own dedicated pvm/texture pack in file order, so no per-enemy slot remapping is
 * needed (see Booma, the first one converted and visually verified). [animationNames] are the raw
 * psov2 .njm entry names within the same bml archive as the model (PRS-compressed only, no PRC
 * encryption -- that's specific to the player's shared plymotiondata.rlc, see Rlc.kt).
 *
 * Boss1 is left out (psov2 doesn't actually implement it -- points at a raw .bin with no
 * model-loading code). Multi-part bosses (De Rol Le, Vol Opt, Dark Falz, Bulclaw, Baranz,
 * Sil Dragon, Dal Ral Lie, Dubchic/Dubchich, Garanz, and their damaged forms) are also left out
 * for now: they assemble several separate .nj fragments into one enemy, which this single-mesh
 * pipeline doesn't handle yet.
 */
sealed class PvmSource {
    class FromBml(val name: String) : PvmSource()
    class FromGsl(val name: String) : PvmSource()
    class Standalone(val fileName: String) : PvmSource()
}

class EnemySpec(
    val slug: String,
    val archive: String,
    val isGsl: Boolean,
    val bmlEntry: String?,
    val pvmSource: PvmSource,
    val njName: String,
    val animationNames: List<String>,
)

val ENEMY_SPECS: List<EnemySpec> = listOf(
    EnemySpec("Rappy", "gsl_forest01.gsl", true, "bm_ene_lappy.bml", PvmSource.FromBml("re3_b_lappy_base.pvm"), "re3_b_lappy_base.nj", listOf("attack_re3_b_base.njm", "damage_re3_b_base.njm", "die_re3_b_base.njm", "run_re3_b_base.njm", "tumble_re3_b_base.njm", "wait_re3_b_base.njm", "wait2_re3_b_base.njm", "wake_re3_b_base.njm", "wake2_re3_b_base.njm", "walk_re3_b_base.njm")),
    EnemySpec("AlRappy", "gsl_forest01.gsl", true, "bm_ene_lappy.bml", PvmSource.FromGsl("re3_b_lappy_base_ao.pvm"), "re3_b_lappy_base.nj", listOf("attack_re3_b_base.njm", "damage_re3_b_base.njm", "die_re3_b_base.njm", "run_re3_b_base.njm", "tumble_re3_b_base.njm", "wait_re3_b_base.njm", "wait2_re3_b_base.njm", "wake_re3_b_base.njm", "wake2_re3_b_base.njm", "walk_re3_b_base.njm")),
    EnemySpec("Booma", "gsl_forest01.gsl", true, "bm_ene_re8_b_beast.bml", PvmSource.FromBml("re8_b_beast_wola_body.pvm"), "re8_b_beast_wola_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("GoBooma", "gsl_forest01.gsl", true, "bm_ene_re8_b_beast.bml", PvmSource.FromBml("re8_b_srdbeast_wola_body.pvm"), "re8_b_srdbeast_wola_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("GigaBooma", "gsl_forest01.gsl", true, "bm_ene_re8_b_beast.bml", PvmSource.FromBml("re8_b_rdbeast_wola_body.pvm"), "re8_b_rdbeast_wola_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("SavageWolf", "gsl_forest01.gsl", true, "bm_ene_bm5_wolf.bml", PvmSource.FromBml("bm5_s_kem_body.pvm"), "bm5_s_kem_body.nj", listOf("dams_bm5_s_kem_body.njm", "deadr_bm5_s_kem_body.njm", "eat_bm5_s_kem_body.njm", "hoe_bm5_s_kem_body.njm", "hunt_bm5_s_kem_body.njm", "okil_bm5_s_kem_body.njm", "okir_bm5_s_kem_body.njm", "run_bm5_s_kem_body.njm", "runb_bm5_s_kem_body.njm", "sleep_bm5_s_kem_body.njm", "stdup_bm5_s_kem_body.njm", "wait_bm5_s_kem_body.njm", "walk_bm5_s_kem_body.njm")),
    EnemySpec("BarbarousWolf", "gsl_forest01.gsl", true, "bm_ene_bm5_wolf.bml", PvmSource.FromBml("bm5_s_kem_body.pvm"), "bm5_s_keml_body.nj", listOf("dams_bm5_s_kem_body.njm", "deadr_bm5_s_kem_body.njm", "eat_bm5_s_kem_body.njm", "hoe_bm5_s_kem_body.njm", "hunt_bm5_s_kem_body.njm", "okil_bm5_s_kem_body.njm", "okir_bm5_s_kem_body.njm", "run_bm5_s_kem_body.njm", "runb_bm5_s_kem_body.njm", "sleep_bm5_s_kem_body.njm", "stdup_bm5_s_kem_body.njm", "wait_bm5_s_kem_body.njm", "walk_bm5_s_kem_body.njm")),
    EnemySpec("Monest", "gsl_forest01.gsl", true, "bm_ene_bm3_fly.bml", PvmSource.FromBml("bm3_fly_body.pvm"), "bm3_s_nest.nj", listOf("dam_bm3_s_nest.njm", "dead_bm3_s_nest.njm", "down_bm3_s_nest.njm", "dwndam_bm3_s_nest.njm", "dwnexit_bm3_s_nest.njm", "dwnwait_bm3_s_nest.njm", "exit_bm3_s_nest.njm", "land_bm3_s_nest.njm", "trance_bm3_s_nest.njm", "wait_bm3_s_nest.njm")),
    EnemySpec("Mothmant", "gsl_forest01.gsl", true, "bm_ene_bm3_fly.bml", PvmSource.FromBml("bm3_fly_body.pvm"), "bm3_fly_body.nj", listOf("atack_bm3_fly_body.njm", "damage_bm3_fly_body.njm", "dead_bm3_fly_body.njm", "fly_bm3_fly_body.njm", "move_bm3_fly_body.njm")),
    EnemySpec("Hildebaby", "gsl_forest02.gsl", true, "bm_ene_bm2_moja.bml", PvmSource.FromBml("bm2c_s_moj_body.pvm"), "bm2c_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Hildebear", "gsl_forest02.gsl", true, "bm_ene_bm2_moja.bml", PvmSource.FromBml("bm2f_s_moj_body.pvm"), "bm2f_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Hildeblue", "gsl_forest02.gsl", true, "bm_ene_bm2_moja.bml", PvmSource.FromBml("bm2w_s_moj_body.pvm"), "bm2w_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Dragon", "bm_boss1_dragon.bml", false, null, PvmSource.FromBml("boss1_s_nb_dragon.pvm"), "boss1_s_nb_dragon.nj", listOf("daml_boss1_s_nb_dragon.njm", "dams_boss1_s_nb_dragon.njm", "dead_boss1_s_nb_dragon.njm", "down_boss1_s_nb_dragon.njm", "fire_boss1_s_nb_dragon.njm", "fly_boss1_s_nb_dragon.njm", "flyshot_boss1_s_nb_dragon.njm", "frin_boss1_s_nb_dragon.njm", "frloop_boss1_s_nb_dragon.njm", "frout_boss1_s_nb_dragon.njm", "kiri_boss1_s_nb_dragon.njm", "land_boss1_s_nb_dragon.njm", "lift_boss1_s_nb_dragon.njm", "nkdown_boss1_s_nb_dragon.njm", "nkup_boss1_s_nb_dragon.njm", "nobi_boss1_s_nb_dragon.njm", "stand_boss1_s_nb_dragon.njm", "tatk_boss1_s_nb_dragon.njm", "tobidasi_boss1_s_nb_dragon.njm", "tukomi_boss1_s_nb_dragon.njm", "walk_boss1_s_nb_dragon.njm", "wgwalk_boss1_s_nb_dragon.njm", "wing_boss1_s_nb_dragon.njm", "wngclose_boss1_s_nb_dragon.njm", "wngopn_boss1_s_nb_dragon.njm")),
    EnemySpec("EvilShark", "gsl_cave01.gsl", true, "bm_ene_bm1_shark.bml", PvmSource.FromBml("bm1_s_wala_body.pvm"), "bm1_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("PalShark", "gsl_cave01.gsl", true, "bm_ene_bm1_shark.bml", PvmSource.FromBml("bm1f_s_wala_body.pvm"), "bm1f_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("GuilShark", "gsl_cave01.gsl", true, "bm_ene_bm1_shark.bml", PvmSource.FromBml("bm1tl_s_wala_body.pvm"), "bm1tl_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("PanArms", "gsl_cave01.gsl", true, "bm7_s_paa_body.bml", PvmSource.FromBml("bm7_s_paa_body.pvm"), "bm7_s_paa_body.nj", listOf("beamdwn_bm7_s_paa_body.njm", "beamup_bm7_s_paa_body.njm", "btamed_bm7_s_paa_body.njm", "btameu_bm7_s_paa_body.njm", "cry_bm7_s_paa_body.njm", "damage_bm7_s_paa_body.njm", "deada_bm7_s_paa_body.njm", "deadb_bm7_s_paa_body.njm", "wait_bm7_s_paa_body.njm", "walk_bm7_s_paa_body.njm", "walkl_bm7_s_paa_body.njm", "walkr_bm7_s_paa_body.njm")),
    EnemySpec("Hidoom", "gsl_cave01.gsl", true, "bm7_s_paa_body.bml", PvmSource.FromBml("bm7_s_pal_body.pvm"), "bm7_s_pal_body.nj", listOf("atack_bm7_s_pal_body.njm", "bunri_bm7_s_pal_body.njm", "damage_bm7_s_pal_body.njm", "deada_bm7_s_pal_body.njm", "deadb_bm7_s_pal_body.njm", "gattai_bm7_s_pal_body.njm", "heal_bm7_s_pal_body.njm", "run_bm7_s_pal_body.njm", "wait_bm7_s_pal_body.njm", "walk_bm7_s_pal_body.njm")),
    EnemySpec("Migium", "gsl_cave01.gsl", true, "bm7_s_paa_body.bml", PvmSource.FromBml("bm7_s_par_body.pvm"), "bm7_s_par_body.nj", listOf("atack_bm7_s_par_body.njm", "bunri_bm7_s_par_body.njm", "damage_bm7_s_par_body.njm", "deada_bm7_s_par_body.njm", "deadb_bm7_s_par_body.njm", "gattai_bm7_s_par_body.njm", "run_bm7_s_par_body.njm", "wait_bm7_s_par_body.njm", "walk_bm7_s_par_body.njm")),
    EnemySpec("MiniGrassAssasin", "gsl_cave01.gsl", true, "bm_ene_cgrass.bml", PvmSource.FromBml("re1c_b_cgrass_base.pvm"), "re1c_b_cgrass_base.nj", listOf("re1c_b_cgrass_base.njm")),
    EnemySpec("GrassAssasin", "gsl_cave01.gsl", true, "bm_ene_grass.bml", PvmSource.FromBml("re1_b_grass_base.pvm"), "re1_b_grass_base.nj", listOf("damege_re1_b_base.njm", "die_re1_b_base.njm", "lattack_re1_b_base.njm", "mad_re1_b_base.njm", "rattack_re1_b_base.njm", "spit_re1_b_base.njm", "wait_re1_b_base.njm", "walk_re1_b_base.njm")),
    EnemySpec("NanoDragoon", "gsl_cave01.gsl", true, "bm_ene_nanodrago.bml", PvmSource.FromBml("bm6_s_drc_body.pvm"), "bm6_s_drc_body.nj", listOf("beam_bm6_s_drc_body.njm", "damfly_bm6_s_drc_body.njm", "damgrd_bm6_s_drc_body.njm", "deadg_bm6_s_drc_body.njm", "deads_bm6_s_drc_body.njm", "fly_bm6_s_drc_body.njm", "joy_bm6_s_drc_body.njm", "land_bm6_s_drc_body.njm", "lasfly_bm6_s_drc_body.njm", "lift_bm6_s_drc_body.njm", "wait_bm6_s_drc_body.njm", "walk_bm6_s_drc_body.njm")),
    EnemySpec("PoisonLily", "gsl_cave01.gsl", true, "bm_ene_re2_flower.bml", PvmSource.FromBml("re2_b_flower_root.pvm"), "re2_b_flower_root.nj", listOf("attack_re2_b_root.njm", "damege_re2_b_root.njm", "die_re2_b_root.njm", "laugh_re2_b_root.njm", "waitc_re2_b_root.njm", "waito_re2_b_root.njm", "wake_re2_b_root.njm")),
    EnemySpec("NarLily", "gsl_cave02.gsl", true, "bm_ene_re2_flower.bml", PvmSource.FromBml("re2_b_flower_root.pvm"), "re2_b_flower_root.nj", listOf("attack_re2_b_root.njm", "damege_re2_b_root.njm", "die_re2_b_root.njm", "laugh_re2_b_root.njm", "waitc_re2_b_root.njm", "waito_re2_b_root.njm", "wake_re2_b_root.njm")),
    EnemySpec("PofuillySlimeBlue", "gsl_cave02.gsl", true, "bm4_ps_ma_body.bml", PvmSource.FromBml("bm4_ps_mb_body.pvm"), "bm4_ps_mbr_body.nj", listOf("atack_bm4_ps_ma_body.njm", "damage_bm4_ps_ma_body.njm", "kie_bm4_ps_ma_body.njm", "nodam_bm4_ps_ma_body.njm", "wait_bm4_ps_ma_body.njm", "wait2_bm4_ps_ma_body.njm", "tlatk_bm4_ps_ma_tail.njm", "apear_bm4_ps_mb_body.njm", "kie_bm4_ps_mb_body.njm", "move_bm4_ps_mb_body.njm", "wait_bm4_ps_mb_body.njm")),
    EnemySpec("PouillySlimeRed", "gsl_cave02.gsl", true, "bm4_ps_ma_body.bml", PvmSource.FromBml("bm4_ps_mbr_body.pvm"), "bm4_ps_mbr_body.nj", listOf("atack_bm4_ps_ma_body.njm", "damage_bm4_ps_ma_body.njm", "kie_bm4_ps_ma_body.njm", "nodam_bm4_ps_ma_body.njm", "wait_bm4_ps_ma_body.njm", "wait2_bm4_ps_ma_body.njm", "tlatk_bm4_ps_ma_tail.njm", "apear_bm4_ps_mb_body.njm", "kie_bm4_ps_mb_body.njm", "move_bm4_ps_mb_body.njm", "wait_bm4_ps_mb_body.njm")),
    EnemySpec("Canadine", "gsl_machine01.gsl", true, "bm_ene_me1_mb.bml", PvmSource.FromBml("me1_y_mb.pvm"), "me1n_y_mb.nj", listOf("change02_me1_y_mb.njm", "change01_me1_y_mb.njm", "damage01_me1_y_mb.njm", "damage02_me1_y_mb.njm", "wait01_me1_y_mb.njm", "wait02_me1_y_mb.njm")),
    EnemySpec("Canane", "gsl_machine01.gsl", true, "bm_ene_me1_mb.bml", PvmSource.FromBml("me1_y_mb.pvm"), "me1_y_mb.nj", listOf("change02_me1_y_mb.njm", "change01_me1_y_mb.njm", "damage01_me1_y_mb.njm", "damage02_me1_y_mb.njm", "wait01_me1_y_mb.njm", "wait02_me1_y_mb.njm")),
    EnemySpec("SinowBeat", "gsl_machine01.gsl", true, "bm_ene_me3_shinowa.bml", PvmSource.FromBml("me3_y_me3.pvm"), "me3_y_me3.nj", listOf("apper_me3_y_me3.njm", "backstep_me3_y_me3.njm", "damage_me3_y_me3.njm", "death_me3_y_me3.njm", "f_attack_me3_y_me3.njm", "sword_me3_y_me3.njm", "transform_me3_y_me3.njm", "t_wait_me3_y_me3.njm", "wait_me3_y_me3.njm")),
    EnemySpec("SinowGold", "gsl_machine01.gsl", true, "bm_ene_me3_shinowa.bml", PvmSource.FromBml("me3_y_me3.pvm"), "me3_y_me3.nj", listOf("apper_me3_y_me3.njm", "backstep_me3_y_me3.njm", "damage_me3_y_me3.njm", "death_me3_y_me3.njm", "f_attack_me3_y_me3.njm", "sword_me3_y_me3.njm", "transform_me3_y_me3.njm", "t_wait_me3_y_me3.njm", "wait_me3_y_me3.njm")),
    EnemySpec("Delsaber", "gsl_ancient01.gsl", true, "bm_ene_df1_saver.bml", PvmSource.FromBml("df1_s_kil_body.pvm"), "df1_s_kil_body.nj", listOf("aseri_df1_s_kil_body.njm", "atack_df1_s_kil_body.njm", "damage_df1_s_kil_body.njm", "deadb_df1_s_kil_body.njm", "dead_df1_s_kil_body.njm", "defdam_df1_s_kil_body.njm", "defence_df1_s_kil_body.njm", "jump_df1_s_kil_body.njm", "nail_df1_s_kil_body.njm", "wait_df1_s_kil_body.njm", "walk_df1_s_kil_body.njm")),
    EnemySpec("Dimenian", "gsl_ancient01.gsl", true, "bm_ene_df3_dimedian.bml", PvmSource.FromBml("df3_s_wala_body.pvm"), "df3_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("LaDimenian", "gsl_ancient01.gsl", true, "bm_ene_df3_dimedian.bml", PvmSource.FromBml("df3_ssl_wala_body.pvm"), "df3_ssl_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("SoDimenian", "gsl_ancient01.gsl", true, "bm_ene_df3_dimedian.bml", PvmSource.FromBml("df3_sl_wala_body.pvm"), "df3_sl_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("ChaosSorcerer", "gsl_ancient01.gsl", true, "bm_ene_re4_sorcerer.bml", PvmSource.FromBml("re4_b_sorcer_body.pvm"), "re4_b_sorcer_body.nj", listOf("attack2_re4_b_body.njm", "attack3_re4_b_body.njm", "attack1_re4_b_body.njm", "cure_re4_b_body.njm", "damage_re4_b_body.njm", "die_re4_b_body.njm", "enter_re4_b_body.njm", "wait_re4_b_body.njm")),
    EnemySpec("DarkBelra", "gsl_ancient01.gsl", true, "bm_ene_re7_berura.bml", PvmSource.FromBml("re7_b_bell_body.pvm"), "re7_b_bell_body.nj", listOf("attack_re7_b_body.njm", "damege_re7_b_body.njm", "die_re7_b_body.njm", "lattack_re7_b_body.njm", "memai_re7_b_body.njm", "rattack_re7_b_body.njm", "wait_re7_b_body.njm", "walk_re7_b_body.njm")),
    EnemySpec("DarkGunner", "gsl_ancient03.gsl", true, "bm_ene_darkgunner.bml", PvmSource.FromBml("re5_b_gunner_body.pvm"), "re5_b_gunner_body.nj", listOf("attack_re5_b_body.njm", "await_re5_b_body.njm", "damage2_re5_b_body.njm", "damage_re5_b_body.njm", "die_re5_b_body.njm", "drop_re5_b_body.njm", "duckdame_re5_b_body.njm", "duckdie_re5_b_body.njm", "duckroop_re5_b_body.njm", "duckwake_re5_b_body.njm", "duck_re5_b_body.njm", "move_re5_b_body.njm", "pullback_re5_b_body.njm", "wait_re5_b_body.njm")),
    EnemySpec("ChaosBringer", "gsl_ancient03.gsl", true, "bm_ene_df2_bringer.bml", PvmSource.FromBml("bm8_s_kb_body.pvm"), "bm8_s_kb_body.nj", listOf("beam_bm8_s_kb_body.njm", "cold_bm8_s_kb_body.njm", "damage_bm8_s_kb_body.njm", "dead_bm8_s_kb_body.njm", "hoe_bm8_s_kb_body.njm", "kamae_bm8_s_kb_body.njm", "kiri_bm8_s_kb_body.njm", "run_bm8_s_kb_body.njm", "tpkyu_bm8_s_kb_body.njm", "wait_bm8_s_kb_body.njm", "walk_bm8_s_kb_body.njm")),
    EnemySpec("Vulmer", "bm_ene_bm1_shark_a.bml", false, null, PvmSource.FromBml("bm1_s_wala_body.pvm"), "bm1_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("GoVulmer", "bm_ene_bm1_shark_a.bml", false, null, PvmSource.FromBml("bm1f_s1_wala_body.pvm"), "bm1f_s1_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Melqueek", "bm_ene_bm1_shark_a.bml", false, null, PvmSource.FromBml("bm1tl_s_wala_body.pvm"), "bm1tl_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("HideltBaby", "bm_ene_bm2_moja_a.bml", false, null, PvmSource.FromBml("bm2c_s_moj_body.pvm"), "bm2c_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Hidelt", "bm_ene_bm2_moja_a.bml", false, null, PvmSource.FromBml("bm2f_s_moj_body.pvm"), "bm2f_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Hildetor", "bm_ene_bm2_moja_a.bml", false, null, PvmSource.FromBml("bm2w_s_moj_body.pvm"), "bm2w_s_moj_body.nj", listOf("cstand_bm2c_s_moj_body.njm", "cwalk_bm2c_s_moj_body.njm", "damage_bm2f_s_moj_body.njm", "dead_bm2f_s_moj_body.njm", "deadb_bm2f_s_moj_body.njm", "giva_bm2f_s_moj_body.njm", "hoe_bm2f_s_moj_body.njm", "jump_bm2f_s_moj_body.njm", "punch_bm2f_s_moj_body.njm", "stand_bm2f_s_moj_body.njm", "walk_bm2f_s_moj_body.njm")),
    EnemySpec("Mothvist", "bm_ene_bm3_fly_a.bml", false, null, PvmSource.FromBml("bm3_fly_body.pvm"), "bm3_s_nest.nj", listOf("dam_bm3_s_nest.njm", "dead_bm3_s_nest.njm", "down_bm3_s_nest.njm", "dwndam_bm3_s_nest.njm", "dwnexit_bm3_s_nest.njm", "dwnwait_bm3_s_nest.njm", "exit_bm3_s_nest.njm", "land_bm3_s_nest.njm", "trance_bm3_s_nest.njm", "wait_bm3_s_nest.njm")),
    EnemySpec("Mothvert", "bm_ene_bm3_fly_a.bml", false, null, PvmSource.FromBml("bm3_fly_body.pvm"), "bm3_fly_body.nj", listOf("atack_bm3_fly_body.njm", "damage_bm3_fly_body.njm", "dead_bm3_fly_body.njm", "fly_bm3_fly_body.njm", "move_bm3_fly_body.njm")),
    EnemySpec("Gulgus", "bm_ene_bm5_wolf_a.bml", false, null, PvmSource.FromBml("bm5_s_kem_body.pvm"), "bm5_s_kem_body.nj", listOf("dams_bm5_s_kem_body.njm", "deadr_bm5_s_kem_body.njm", "eat_bm5_s_kem_body.njm", "hoe_bm5_s_kem_body.njm", "hunt_bm5_s_kem_body.njm", "okil_bm5_s_kem_body.njm", "okir_bm5_s_kem_body.njm", "run_bm5_s_kem_body.njm", "runb_bm5_s_kem_body.njm", "sleep_bm5_s_kem_body.njm", "stdup_bm5_s_kem_body.njm", "wait_bm5_s_kem_body.njm", "walk_bm5_s_kem_body.njm")),
    EnemySpec("GulgusGue", "bm_ene_bm5_wolf_a.bml", false, null, PvmSource.FromBml("bm5_s_kem_body.pvm"), "bm5_s_keml_body.nj", listOf("dams_bm5_s_kem_body.njm", "deadr_bm5_s_kem_body.njm", "eat_bm5_s_kem_body.njm", "hoe_bm5_s_kem_body.njm", "hunt_bm5_s_kem_body.njm", "okil_bm5_s_kem_body.njm", "okir_bm5_s_kem_body.njm", "run_bm5_s_kem_body.njm", "runb_bm5_s_kem_body.njm", "sleep_bm5_s_kem_body.njm", "stdup_bm5_s_kem_body.njm", "wait_bm5_s_kem_body.njm", "walk_bm5_s_kem_body.njm")),
    EnemySpec("MiniCrimsonAssassin", "bm_ene_cgrass_a.bml", false, null, PvmSource.FromBml("re1c_b_cgrass_base.pvm"), "re1c_b_cgrass_base.nj", listOf("re1c_b_cgrass_base.njm")),
    EnemySpec("CrimsonAssassin", "bm_ene_grass_a.bml", false, null, PvmSource.FromBml("re1_b_grass_base.pvm"), "re1_b_grass_base.nj", listOf("damege_re1_b_base.njm", "die_re1_b_base.njm", "lattack_re1_b_base.njm", "mad_re1_b_base.njm", "rattack_re1_b_base.njm", "spit_re1_b_base.njm", "wait_re1_b_base.njm", "walk_re1_b_base.njm")),
    EnemySpec("DarkBringer", "bm_ene_df2_bringer_a.bml", false, null, PvmSource.FromBml("bm8_s_kb_body.pvm"), "bm8_s_kb_body.nj", listOf("beam_bm8_s_kb_body.njm", "cold_bm8_s_kb_body.njm", "damage_bm8_s_kb_body.njm", "dead_bm8_s_kb_body.njm", "hoe_bm8_s_kb_body.njm", "kamae_bm8_s_kb_body.njm", "kiri_bm8_s_kb_body.njm", "run_bm8_s_kb_body.njm", "tpkyu_bm8_s_kb_body.njm", "wait_bm8_s_kb_body.njm", "walk_bm8_s_kb_body.njm")),
    EnemySpec("Arlan", "bm_ene_df3_dimedian_a.bml", false, null, PvmSource.FromBml("df3_s_wala_body.pvm"), "df3_s_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Merlan", "bm_ene_df3_dimedian_a.bml", false, null, PvmSource.FromBml("df3_ssl_wala_body.pvm"), "df3_ssl_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("DelD", "bm_ene_df3_dimedian_a.bml", false, null, PvmSource.FromBml("df3_sl_wala_body.pvm"), "df3_sl_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Canabin", "bm_ene_me1_mb_a.bml", false, null, PvmSource.FromBml("me1_y_mb.pvm"), "me1n_y_mb.nj", listOf("change02_me1_y_mb.njm", "change01_me1_y_mb.njm", "damage01_me1_y_mb.njm", "damage02_me1_y_mb.njm", "wait01_me1_y_mb.njm", "wait02_me1_y_mb.njm")),
    EnemySpec("Canune", "bm_ene_me1_mb_a.bml", false, null, PvmSource.FromBml("me1_y_mb.pvm"), "me1_y_mb.nj", listOf("change02_me1_y_mb.njm", "change01_me1_y_mb.njm", "damage01_me1_y_mb.njm", "damage02_me1_y_mb.njm", "wait01_me1_y_mb.njm", "wait02_me1_y_mb.njm")),
    EnemySpec("SinowBlue", "bm_ene_me3_shinowa_a.bml", false, null, PvmSource.FromBml("me3_y_me3.pvm"), "me3_y_me3.nj", listOf("apper_me3_y_me3.njm", "backstep_me3_y_me3.njm", "damage_me3_y_me3.njm", "death_me3_y_me3.njm", "f_attack_me3_y_me3.njm", "sword_me3_y_me3.njm", "transform_me3_y_me3.njm", "t_wait_me3_y_me3.njm", "wait_me3_y_me3.njm")),
    EnemySpec("SinowRed", "bm_ene_me3_shinowa_a.bml", false, null, PvmSource.FromBml("me3_y_me3.pvm"), "me3_y_me3.nj", listOf("apper_me3_y_me3.njm", "backstep_me3_y_me3.njm", "damage_me3_y_me3.njm", "death_me3_y_me3.njm", "f_attack_me3_y_me3.njm", "sword_me3_y_me3.njm", "transform_me3_y_me3.njm", "t_wait_me3_y_me3.njm", "wait_me3_y_me3.njm")),
    EnemySpec("ObLily", "bm_ene_re2_flower_a.bml", false, null, PvmSource.FromBml("flower_root.pvm"), "flower_root.nj", listOf("attack_re2_b_root.njm", "damege_re2_b_root.njm", "die_re2_b_root.njm", "laugh_re2_b_root.njm", "waitc_re2_b_root.njm", "waito_re2_b_root.njm", "wake_re2_b_root.njm")),
    EnemySpec("MilLily", "bm_ene_re2_flower_a.bml", false, null, PvmSource.FromBml("flower_root.pvm"), "flower_root.nj", listOf("attack_re2_b_root.njm", "damege_re2_b_root.njm", "die_re2_b_root.njm", "laugh_re2_b_root.njm", "waitc_re2_b_root.njm", "waito_re2_b_root.njm", "wake_re2_b_root.njm")),
    EnemySpec("GranSorcerer", "bm_ene_re4_sorcerer_a.bml", false, null, PvmSource.FromBml("re4_b_sorcer_body.pvm"), "re4_b_sorcer_body.nj", listOf("attack2_re4_b_body.njm", "attack3_re4_b_body.njm", "attack1_re4_b_body.njm", "cure_re4_b_body.njm", "damage_re4_b_body.njm", "die_re4_b_body.njm", "enter_re4_b_body.njm", "wait_re4_b_body.njm")),
    EnemySpec("IndiBelra", "bm_ene_re7_berura_a.bml", false, null, PvmSource.FromBml("re7_b_bell_body.pvm"), "re7_b_bell_body.nj", listOf("attack_re7_b_body.njm", "damege_re7_b_body.njm", "die_re7_b_body.njm", "lattack_re7_b_body.njm", "memai_re7_b_body.njm", "rattack_re7_b_body.njm", "wait_re7_b_body.njm", "walk_re7_b_body.njm")),
    EnemySpec("Bartle", "bm_ene_re8_b_beast_a.bml", false, null, PvmSource.FromBml("re8_b_beast_wala_body.pvm"), "re8_b_beast_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Barble", "bm_ene_re8_b_beast_a.bml", false, null, PvmSource.FromBml("re8_b_srbeast_wala_body.pvm"), "re8_b_srbeast_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Tollaw", "bm_ene_re8_b_beast_a.bml", false, null, PvmSource.FromBml("re8_rdbeast_wala_body.pvm"), "re8_rdbeast_wala_body.nj", listOf("appear_bm1_s_wala_body.njm", "atackl_bm1_s_wala_body.njm", "atackr_bm1_s_wala_body.njm", "damage_bm1_s_wala_body.njm", "dead_bm1_s_wala_body.njm", "deadb_bm1_s_wala_body.njm", "leader_bm1_s_wala_body.njm", "mihari_bm1_s_wala_body.njm", "run_bm1_s_wala_body.njm", "stund_bm1_s_wala_body.njm", "wakeup_bm1_s_wala_body.njm", "walk_bm1_s_wala_body.njm")),
    EnemySpec("Gillchich", "bm_ene_dubchik_a.bml", false, null, PvmSource.Standalone("me2_y_me2_z_a.pvm"), "me2_y_me2.nj", listOf("damage_b_me2_y_me2.njm", "damage_f_me2_y_me2.njm", "kamae01_me2_y_me2.njm", "kamae02_me2_y_me2.njm", "revival_b_me2_y_me2.njm", "revival_f_me2_y_me2.njm", "scratch01_me2_me2.njm", "scratch02_me2_y_me2.njm", "shoot01_me2_y_me2.njm", "shoot02_me2_me2.njm", "starting_me2_y_me2.njm", "wait01_me2_y_me2.njm", "wait02_me2_y_me2.njm", "walk01_me2_y_me2.njm", "walk02_me2_y_me2.njm")),
    EnemySpec("Gilchic", "gsl_machine01.gsl", true, "bm_ene_dubchik.bml", PvmSource.Standalone("me2_y_me2_z.pvm"), "me2_y_me2.nj", listOf("damage_b_me2_y_me2.njm", "damage_f_me2_y_me2.njm", "kamae01_me2_y_me2.njm", "kamae02_me2_y_me2.njm", "revival_b_me2_y_me2.njm", "revival_f_me2_y_me2.njm", "scratch01_me2_me2.njm", "scratch02_me2_y_me2.njm", "shoot01_me2_y_me2.njm", "shoot02_me2_me2.njm", "starting_me2_y_me2.njm", "wait01_me2_y_me2.njm", "wait02_me2_y_me2.njm", "walk01_me2_y_me2.njm", "walk02_me2_y_me2.njm")),
    EnemySpec("ElRappy", "bm_ene_lappy_ap.bml", false, null, PvmSource.FromBml("re3_b_lappy_base.pvm"), "re3_b_lappy_base.nj", listOf("attack_re3_b_base.njm", "damage_re3_b_base.njm", "die_re3_b_base.njm", "run_re3_b_base.njm", "tumble_re3_b_base.njm", "wait_re3_b_base.njm", "wait2_re3_b_base.njm", "wake_re3_b_base.njm", "wake2_re3_b_base.njm", "walk_re3_b_base.njm")),
    EnemySpec("PalRappy", "bm_ene_lappy_ap.bml", false, null, PvmSource.Standalone("re3_b_lappy_base_niji.pvm"), "re3_b_lappy_base.nj", listOf("attack_re3_b_base.njm", "damage_re3_b_base.njm", "die_re3_b_base.njm", "run_re3_b_base.njm", "tumble_re3_b_base.njm", "wait_re3_b_base.njm", "wait2_re3_b_base.njm", "wake_re3_b_base.njm", "wake2_re3_b_base.njm", "walk_re3_b_base.njm")),
)
