package world.phantasmal.web.assetsGeneration.psov2

/**
 * One weapon (or shield/mag/unit -- psov2's own AssetWeapons.js bundles all of PSO's handheld and
 * wearable item models together under one "weapons" category, so this mirrors that) from psov2's
 * shared item archives. Unlike enemies/maps, every item's model and texture live in the same two
 * archives (itemmodel.afs / itemtexture.afs) indexed by position, PRS-compressed per entry (unlike
 * the uncompressed AFS archives psolib's own parseAfs was written for, e.g. player textures --
 * see GeneratePsov2MobileAssets.kt's generateWeapons). [texIndex]/[modelIndex] are usually the
 * same value, but several palette-swap variants (e.g. the four elemental Gods Shields) reuse
 * another item's [modelIndex] with their own distinct [texIndex]. Auto-generated via Python regex
 * extraction against psov2's AssetWeapons.js (227 entries, all of episode 1's non-rare item
 * visuals plus debug/test items).
 */
class WeaponSpec(
    val slug: String,
    val displayName: String,
    val texIndex: Int,
    val modelIndex: Int,
)

val WEAPON_SPECS: List<WeaponSpec> = listOf(
    WeaponSpec("Saber", "Saber", 0, 0),
    WeaponSpec("Sword", "Sword", 1, 1),
    WeaponSpec("Dagger", "Dagger", 2, 2),
    WeaponSpec("Partisan", "Partisan", 3, 3),
    WeaponSpec("Slicer", "Slicer", 4, 4),
    WeaponSpec("Handgun", "Handgun", 5, 5),
    WeaponSpec("Rifle", "Rifle", 6, 6),
    WeaponSpec("Mechgun", "Mechgun", 7, 7),
    WeaponSpec("Shot", "Shot", 8, 8),
    WeaponSpec("Cane", "Cane", 9, 9),
    WeaponSpec("Rod", "Rod", 10, 10),
    WeaponSpec("Wand", "Wand", 11, 11),
    WeaponSpec("Claw", "Claw", 12, 12),
    WeaponSpec("DoubleSaber", "DoubleSaber", 13, 13),
    WeaponSpec("SonicKnuckle", "Sonic Knuckle", 14, 14),
    WeaponSpec("Orotiagito", "Orotiagito", 15, 15),
    WeaponSpec("SoulEater", "Soul Eater", 16, 16),
    WeaponSpec("SpreadNeedle", "Spread Needle", 17, 17),
    WeaponSpec("HolyRay", "Holy Ray", 18, 18),
    WeaponSpec("InfernoBazooka", "Inferno Bazooka", 19, 19),
    WeaponSpec("FlameVisit", "Flame Visit", 20, 20),
    WeaponSpec("Akiko", "Akiko", 21, 21),
    WeaponSpec("Sorcerer", "Sorcerer", 22, 22),
    WeaponSpec("SBeat", "S-Beat", 23, 23),
    WeaponSpec("PArm", "P-Arm", 24, 24),
    WeaponSpec("Delsaber", "Delsaber", 25, 25),
    WeaponSpec("BringerRifle", "Bringer Rifle", 26, 26),
    WeaponSpec("EggBlaster", "Egg Blaster", 27, 27),
    WeaponSpec("PsychoWand", "Psycho Wand", 28, 28),
    WeaponSpec("HeavensPunisher", "Heavens Punisher", 29, 29),
    WeaponSpec("LavisCannon", "Lavis Cannon", 30, 30),
    WeaponSpec("VictorAxe", "Victor Axe", 31, 31),
    WeaponSpec("ChainSawd", "Chain Sawd", 32, 32),
    WeaponSpec("Caduceus", "Caduceus", 33, 33),
    WeaponSpec("StingTip", "Sting Tip", 34, 34),
    WeaponSpec("MagicalPiece", "Magical Piece", 35, 35),
    WeaponSpec("TechnicalCrozier", "Technical Crozier", 36, 36),
    WeaponSpec("SuppressedGun", "Suppressed Gun", 37, 37),
    WeaponSpec("AncientSaber", "Ancient Saber", 38, 38),
    WeaponSpec("HarisenBattleFan", "Harisen Battle Fan", 39, 39),
    WeaponSpec("Yamigarasu", "Yamigarasu", 40, 40),
    WeaponSpec("AkikoWok", "Akiko Wok", 41, 41),
    WeaponSpec("ToyHammer", "Toy Hammer", 42, 42),
    WeaponSpec("Elysion", "Elysion", 43, 43),
    WeaponSpec("RedSaber", "Red Saber", 44, 44),
    WeaponSpec("MeteorCudgel", "Meteor Cudgel", 45, 45),
    WeaponSpec("MonkeyKingBar", "Monkey King Bar", 46, 46),
    WeaponSpec("DoubleCannon", "Double Cannon", 47, 47),
    WeaponSpec("HugeBattleFan", "Huge Battle Fan", 48, 48),
    WeaponSpec("TsumikiriJSword", "Tsumikiri J-Sword", 49, 49),
    WeaponSpec("SealedJSword", "Sealed J-Sword", 50, 50),
    WeaponSpec("RedSword", "Red Sword", 51, 51),
    WeaponSpec("CrazyTune", "Crazy Tune", 52, 52),
    WeaponSpec("TwinChakram", "Twin Chakram", 53, 53),
    WeaponSpec("WokOfAkiko", "Wok of Akiko", 54, 54),
    WeaponSpec("LavisBlade", "Lavis Blade", 55, 55),
    WeaponSpec("RedDagger", "Red Dagger", 56, 56),
    WeaponSpec("MaddamPink", "Maddam Pink", 57, 57),
    WeaponSpec("MaddamPurple", "Maddam Purple", 58, 58),
    WeaponSpec("ImperialPick", "Imperial Pick", 59, 59),
    WeaponSpec("Berdysh", "Berdysh", 60, 60),
    WeaponSpec("RedPartisan", "Red Partisan", 61, 61),
    WeaponSpec("FlightCutter", "Flight Cutter", 62, 62),
    WeaponSpec("FlightFan", "Flight Fan", 63, 63),
    WeaponSpec("RedSlicer", "Red Slicer", 64, 64),
    WeaponSpec("HandgunGuld", "Handgun Guld", 65, 65),
    WeaponSpec("HandgunMilla", "Handgun Milla", 66, 66),
    WeaponSpec("RedHandgun", "Red Handgun", 67, 67),
    WeaponSpec("FrozenShooter", "Frozen Shooter", 68, 68),
    WeaponSpec("AntiAndroidRifle", "Anti-Android Rifle", 69, 69),
    WeaponSpec("RocketPunch", "Rocket Punch", 70, 70),
    WeaponSpec("SambaMaracas", "Samba Maracas", 71, 71),
    WeaponSpec("TwinPsychogun", "Twin Psychogun", 72, 72),
    WeaponSpec("DrillLauncher", "Drill Launcher", 73, 73),
    WeaponSpec("GuldMilla", "Guld Milla", 74, 74),
    WeaponSpec("RedMechguns", "Red Mechguns", 75, 75),
    WeaponSpec("BelraCannon", "Belra Cannon", 76, 76),
    WeaponSpec("PanzerFaust", "Panzer Faust", 77, 77),
    WeaponSpec("SummitMoon", "Summit Moon", 78, 78),
    WeaponSpec("Windmill", "Windmill", 79, 79),
    WeaponSpec("EvilCurst", "Evil Curst", 80, 80),
    WeaponSpec("FlowerCane", "Flower Cane", 81, 81),
    WeaponSpec("Hildebear", "Hildebear", 82, 82),
    WeaponSpec("Hildeblue", "Hildeblue", 83, 83),
    WeaponSpec("RabbitWand", "Rabbit Wand", 84, 84),
    WeaponSpec("PlantainLeaf", "Plantain Leaf", 85, 85),
    WeaponSpec("DemonicFork", "Demonic Fork", 86, 86),
    WeaponSpec("StrikerOfChao", "Striker of Chao", 87, 87),
    WeaponSpec("Broom", "Broom", 88, 88),
    WeaponSpec("ProphetsOfMotav", "Prophets of Motav", 89, 89),
    WeaponSpec("TheSighOfAGod", "The Sigh of a God", 90, 90),
    WeaponSpec("TwinkleStar", "Twinkle Star", 91, 91),
    WeaponSpec("PlantainFan", "Plantain Fan", 92, 92),
    WeaponSpec("TwinBlaze", "Twin Blaze", 93, 93),
    WeaponSpec("Marina", "Marina", 94, 94),
    WeaponSpec("DragonClaw", "Dragon Claw", 95, 95),
    WeaponSpec("PantherClaw", "Panther Claw", 96, 96),
    WeaponSpec("SRankDagger", "S-Rank Dagger", 97, 97),
    WeaponSpec("PlantainHugeFan", "Plantain Huge Fan", 98, 98),
    WeaponSpec("ChameleonScythe", "Chameleon Scythe", 99, 99),
    WeaponSpec("Yasminkov3000r", "Yasminkov 3000r", 100, 100),
    WeaponSpec("AnoRifle", "Ano Rifle", 101, 101),
    WeaponSpec("BaranzLauncher", "Baranz Launcher", 102, 102),
    WeaponSpec("BranchOfPakuPaku", "Branch of Paku Paku", 103, 103),
    WeaponSpec("HeartOfPoumn", "Heart of Poumn", 104, 104),
    WeaponSpec("Yasminkov2000h", "Yasminkov 2000h", 105, 105),
    WeaponSpec("Yasminkov7000v", "Yasminkov 7000v", 106, 106),
    WeaponSpec("Yasminkov9000m", "Yasminkov 9000m", 107, 107),
    WeaponSpec("MaserBeam", "Maser Beam", 108, 108),
    WeaponSpec("GameMagazine", "Game Magazine", 109, 109),
    WeaponSpec("FlowerBouquet", "Flower Bouquet", 110, 110),
    WeaponSpec("SRankSaber", "S-Rank Saber", 111, 111),
    WeaponSpec("SRankSword", "S-Rank Sword", 112, 112),
    WeaponSpec("SRankBlade", "S-Rank Blade", 113, 113),
    WeaponSpec("SRankPartisan", "S-Rank Partisan", 114, 114),
    WeaponSpec("SRankSlicer", "S-Rank Slicer", 115, 115),
    WeaponSpec("SRankGun", "S-Rank Gun", 116, 116),
    WeaponSpec("SRankRifle", "S-Rank Rifle", 117, 117),
    WeaponSpec("SRankMechgun", "S-Rank Mechgun", 118, 118),
    WeaponSpec("SRankShot", "S-Rank Shot", 119, 119),
    WeaponSpec("SRankCane", "S-Rank Cane", 120, 120),
    WeaponSpec("SRankRod", "S-Rank Rod", 121, 121),
    WeaponSpec("SRankWand", "S-Rank Wand", 122, 122),
    WeaponSpec("SRankTwin", "S-Rank Twin", 123, 123),
    WeaponSpec("SRankClaw", "S-Rank Claw", 124, 124),
    WeaponSpec("SRankBazooka", "S-Rank Bazooka", 125, 125),
    WeaponSpec("SRankNeedle", "S-Rank Needle", 126, 126),
    WeaponSpec("SRankScythe", "S-Rank Scythe", 127, 127),
    WeaponSpec("SRankHammer", "S-Rank Hammer", 128, 128),
    WeaponSpec("SRankMoon", "S-Rank Moon", 129, 129),
    WeaponSpec("SRankPsychogun", "S-Rank Psychogun", 130, 130),
    WeaponSpec("SRankPunch", "S-Rank Punch", 131, 131),
    WeaponSpec("SRankWindmill", "S-Rank Windmill", 132, 132),
    WeaponSpec("SRankHarisen", "S-Rank Harisen", 133, 133),
    WeaponSpec("SRankKatana", "S-Rank Katana", 134, 134),
    WeaponSpec("SRankJCutter", "S-Rank J-Cutter", 135, 135),
    WeaponSpec("DebugSaber", "Debug Saber", 136, 136),
    WeaponSpec("DebugSword", "Debug Sword", 138, 138),
    WeaponSpec("DebugDagger", "Debug Dagger", 139, 139),
    WeaponSpec("DebugPartisan", "Debug Partisan", 140, 140),
    WeaponSpec("DebugSlicer", "Debug Slicer", 141, 141),
    WeaponSpec("DebugHandgun", "Debug Handgun", 142, 142),
    WeaponSpec("DebugRifle", "Debug Rifle", 143, 143),
    WeaponSpec("DebugMechgun", "Debug Mechgun", 144, 144),
    WeaponSpec("DebugShot", "Debug Shot", 145, 145),
    WeaponSpec("DebugCane", "Debug Cane", 146, 146),
    WeaponSpec("DebugRod", "Debug Rod", 147, 147),
    WeaponSpec("DebugWand", "Debug Wand", 148, 148),
    WeaponSpec("DebugClaw", "Debug Claw", 149, 149),
    WeaponSpec("DebugDoubleSaber", "Debug DoubleSaber", 150, 150),
    WeaponSpec("Mag", "Mag", 151, 151),
    WeaponSpec("Varuna", "Varuna", 152, 152),
    WeaponSpec("Mitra", "Mitra", 153, 153),
    WeaponSpec("Surya", "Surya", 154, 154),
    WeaponSpec("Vayu", "Vayu", 155, 155),
    WeaponSpec("Varaha", "Varaha", 156, 156),
    WeaponSpec("Kama", "Kama", 157, 157),
    WeaponSpec("Ushasu", "Ushasu", 158, 158),
    WeaponSpec("Apsaras", "Apsaras", 159, 159),
    WeaponSpec("Kumara", "Kumara", 160, 160),
    WeaponSpec("Kaitabha", "Kaitabha", 161, 161),
    WeaponSpec("Tapas", "Tapas", 162, 162),
    WeaponSpec("Bhirava", "Bhirava", 163, 163),
    WeaponSpec("Kalki", "Kalki", 164, 164),
    WeaponSpec("Rudra", "Rudra", 165, 165),
    WeaponSpec("Marutah", "Marutah", 166, 166),
    WeaponSpec("Yaksa", "Yaksa", 167, 167),
    WeaponSpec("Sita", "Sita", 168, 168),
    WeaponSpec("Garuda", "Garuda", 169, 169),
    WeaponSpec("Nandin", "Nandin", 170, 170),
    WeaponSpec("Ashvinau", "Ashvinau", 171, 171),
    WeaponSpec("Ribhava", "Ribhava", 172, 172),
    WeaponSpec("Soma", "Soma", 173, 173),
    WeaponSpec("Ila", "Ila", 174, 174),
    WeaponSpec("Durga", "Durga", 175, 175),
    WeaponSpec("Vritra", "Vritra", 176, 176),
    WeaponSpec("Namuci", "Namuci", 177, 177),
    WeaponSpec("Sumba", "Sumba", 178, 178),
    WeaponSpec("Naga", "Naga", 179, 179),
    WeaponSpec("Pitri", "Pitri", 180, 180),
    WeaponSpec("Kabanda", "Kabanda", 181, 181),
    WeaponSpec("Ravana", "Ravana", 182, 182),
    WeaponSpec("Marica", "Marica", 183, 183),
    WeaponSpec("Soniti", "Soniti", 184, 184),
    WeaponSpec("Pretra", "Pretra", 185, 185),
    WeaponSpec("Andhaka", "Andhaka", 186, 186),
    WeaponSpec("Bana", "Bana", 187, 187),
    WeaponSpec("Naraka", "Naraka", 188, 188),
    WeaponSpec("Madhu", "Madhu", 189, 189),
    WeaponSpec("Churel", "Churel", 190, 190),
    WeaponSpec("RoboChao", "Robo Chao", 191, 191),
    WeaponSpec("OpaOpa", "Opa Opa", 192, 192),
    WeaponSpec("Pian", "Pian", 193, 193),
    WeaponSpec("Chao", "Chao", 194, 194),
    WeaponSpec("ChuChu", "Chu Chu", 195, 195),
    WeaponSpec("KapuKapu", "Kapu Kapu", 196, 196),
    WeaponSpec("AngelWings", "Angel Wings", 197, 197),
    WeaponSpec("DevilWings", "Devil Wings", 198, 198),
    WeaponSpec("Elnoa", "Elnoa", 199, 199),
    WeaponSpec("MarkIII", "Mark III", 200, 200),
    WeaponSpec("MasterSystem", "Master System", 201, 201),
    WeaponSpec("Genesis", "Genesis", 202, 202),
    WeaponSpec("SegaSaturn", "Sega Saturn", 203, 203),
    WeaponSpec("Dreamcast", "Dreamcast", 204, 204),
    WeaponSpec("Hamburger", "Hamburger", 205, 205),
    WeaponSpec("PanzerTail", "Panzer Tail", 206, 206),
    WeaponSpec("DevilTail", "Devil Tail", 207, 207),
    WeaponSpec("DebugMag", "Debug Mag", 208, 208),
    WeaponSpec("RedRing", "Red Ring", 209, 209),
    WeaponSpec("TripolicShield", "Tripolic Shield", 210, 210),
    WeaponSpec("StandstillShield", "Standstill Shield", 211, 211),
    WeaponSpec("SafetyHeart", "Safety Heart", 212, 212),
    WeaponSpec("KasamiBracer", "Kasami Bracer", 213, 213),
    WeaponSpec("GodsShieldSuzaku", "Gods Shield Suzaku", 214, 214),
    WeaponSpec("GodsShieldGenbu", "Gods Shield Genbu", 215, 214),
    WeaponSpec("GodsShieldByakko", "Gods Shield Byakko", 216, 214),
    WeaponSpec("GodsShieldSeiryu", "Gods Shield Seiryu", 217, 214),
    WeaponSpec("HunterShield", "Hunter Shield", 218, 218),
    WeaponSpec("RicoGlasses", "Rico Glasses", 219, 219),
    WeaponSpec("RicoEarings", "Rico Earings", 220, 220),
    WeaponSpec("BlueRing", "Blue Ring", 221, 221),
    WeaponSpec("YellowRing", "Yellow Ring", 222, 222),
    WeaponSpec("SecureFeet", "Secure Feet", 223, 223),
    WeaponSpec("PurpleRing", "Purple Ring", 224, 224),
    WeaponSpec("GreenRing", "Green Ring", 225, 225),
    WeaponSpec("BlackRing", "Black Ring", 226, 226),
    WeaponSpec("WhiteRing", "White Ring", 227, 227),
)
